"""Add email_confirmed field to profiles

Revision ID: 6eaa2b66f7ff
Revises: 8b47e12af44c
Create Date: 2025-11-01 13:08:50.643101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eaa2b66f7ff'
down_revision: Union[str, Sequence[str], None] = '8b47e12af44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'email_confirmed')
    # ### end Alembic commands ###
